"""store cluster analysis data. add created dates to all models

Revision ID: 0a2e13661fba
Revises: 188af1a162cf
Create Date: 2025-03-13 14:42:45.597432

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a2e13661fba'
down_revision = '188af1a162cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visualization_data', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('visualization_mime_type', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('report_data', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('report_mime_type', sa.Text(), nullable=False))
        batch_op.drop_column('report_path')
        batch_op.drop_column('visualization_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visualization_path', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('report_path', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('report_mime_type')
        batch_op.drop_column('report_data')
        batch_op.drop_column('visualization_mime_type')
        batch_op.drop_column('visualization_data')

    # ### end Alembic commands ###
