"""remove cil process

Revision ID: 188af1a162cf
Revises: f110d41dcb18
Create Date: 2025-03-13 14:20:04.510100

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '188af1a162cf'
down_revision = 'f110d41dcb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cil_process')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cil_process',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reference_file', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('cil_output_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ifs_output_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cil_process_pkey')
    )
    # ### end Alembic commands ###
