"""fixup plan data collection model

Revision ID: 524a37dc408f
Revises: 0a2e13661fba
Create Date: 2025-03-14 08:55:54.681800

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '524a37dc408f'
down_revision = '0a2e13661fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_data_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('failed_urls', sa.Text(), nullable=True))
        batch_op.drop_column('output_path')
        batch_op.drop_column('failed_urls_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_data_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_urls_path', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('output_path', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('failed_urls')
        batch_op.drop_column('data')

    # ### end Alembic commands ###
