"""add models for other analysis runs/results

Revision ID: f110d41dcb18
Revises: 6d804cb18ab9
Create Date: 2025-03-12 11:14:54.794540

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f110d41dcb18'
down_revision = '6d804cb18ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cil_process',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('reference_file', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cil_output_path', sa.Text(), nullable=False),
    sa.Column('ifs_output_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('grouped_reasons', sa.JSON(), nullable=False),
    sa.Column('visualization_path', sa.Text(), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_data_collection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('reference_file', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=False),
    sa.Column('failed_urls_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_data_collection')
    op.drop_table('cluster_analysis')
    op.drop_table('cil_process')
    # ### end Alembic commands ###
