"""initial migration

Revision ID: f2696acb6397
Revises:
Create Date: 2025-02-25 13:07:00.052815

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f2696acb6397'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extract',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extract_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('extract_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['extract_id'], ['extract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extract_item')
    op.drop_table('extract')
    # ### end Alembic commands ###
